pipefail tweaks

diff --git a/config_h_gen b/config_h_gen
--- a/config_h_gen
+++ b/config_h_gen
@@ -1,5 +1,9 @@
 #! /bin/sh
-set -euf -o pipefail
+
+# We'd like pipes to fail properly, but we don't quite depend on it anywhere.
+# Try to enable, but also try not to die if it doesn't work.
+set -o pipefail >/dev/null || true
+set -euf
 
 if [ $# -lt 2 ]; then
 	echo "Usage: $0 <input-file> <cc> <cflags>..."
